<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="C4EventB" nsURI="http://ac/soton/eventb/c" nsPrefix="ac.soton.eventb.c">
  <eClassifiers xsi:type="ecore:EClass" name="CNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CType" eSuperTypes="#//CNamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CVariable" eSuperTypes="#//CNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConstant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CStruct" eSuperTypes="#//CNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//CField" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CField" eSuperTypes="#//CNamedElement #//CType"/>
  <eClassifiers xsi:type="ecore:EClass" name="CEnumeration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EnumerationLiterals" ordered="false"
        upperBound="-1" eType="#//CNamedElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CArray" eSuperTypes="#//CType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrayElements" upperBound="-1"
        eType="#//CArrayElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CArrayElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CPointer" eSuperTypes="#//CNamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CProject" eSuperTypes="#//CNamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="CFunction"/>
  <eClassifiers xsi:type="ecore:EClass" name="CHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="CDerivedType"/>
  <eClassifiers xsi:type="ecore:EClass" name="CDiscreteType"/>
</ecore:EPackage>
