/*
 * generated by Xtext 2.25.0
 */
package ac.soton.xtext.c.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractXcScopeProvider extends DelegatingScopeProvider {
}
