/*
 * generated by Xtext 2.25.0
 */
package ac.soton.xtext.c.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class XcUiModule extends AbstractXcUiModule {

	public XcUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
