/**
 * generated by Xtext 2.25.0
 */
package ac.soton.xtext.c.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(XcInjectorProvider.class)
@SuppressWarnings("all")
public class XcParsingTest {
  @Inject
  private /* ParseHelper<CTranslationUnit> */Object parseHelper;

  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field XcParsingTest.parseHelper refers to the missing type CTranslationUnit"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
