/*
 * generated by Xtext 2.25.0
 */
package ac.soton.xtext.c.ide.contentassist.antlr;

import ac.soton.xtext.c.ide.contentassist.antlr.internal.InternalXcParser;
import ac.soton.xtext.c.services.XcGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class XcParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(XcGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, XcGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getCSubProgramAccess().getAlternatives(), "rule__CSubProgram__Alternatives");
			builder.put(grammarAccess.getCVariableAccess().getAlternatives(), "rule__CVariable__Alternatives");
			builder.put(grammarAccess.getCTypeAccess().getAlternatives(), "rule__CType__Alternatives");
			builder.put(grammarAccess.getCExpressionAccess().getAlternatives(), "rule__CExpression__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getCTranslationUnitAccess().getGroup(), "rule__CTranslationUnit__Group__0");
			builder.put(grammarAccess.getCTranslationUnitAccess().getGroup_4(), "rule__CTranslationUnit__Group_4__0");
			builder.put(grammarAccess.getCTranslationUnitAccess().getGroup_5(), "rule__CTranslationUnit__Group_5__0");
			builder.put(grammarAccess.getCTranslationUnitAccess().getGroup_5_3(), "rule__CTranslationUnit__Group_5_3__0");
			builder.put(grammarAccess.getCTranslationUnitAccess().getGroup_6(), "rule__CTranslationUnit__Group_6__0");
			builder.put(grammarAccess.getCTranslationUnitAccess().getGroup_6_3(), "rule__CTranslationUnit__Group_6_3__0");
			builder.put(grammarAccess.getCSourceFileAccess().getGroup(), "rule__CSourceFile__Group__0");
			builder.put(grammarAccess.getCSourceFileAccess().getGroup_4(), "rule__CSourceFile__Group_4__0");
			builder.put(grammarAccess.getCSourceFileAccess().getGroup_5(), "rule__CSourceFile__Group_5__0");
			builder.put(grammarAccess.getCSourceFileAccess().getGroup_5_3(), "rule__CSourceFile__Group_5_3__0");
			builder.put(grammarAccess.getCSourceFileAccess().getGroup_6(), "rule__CSourceFile__Group_6__0");
			builder.put(grammarAccess.getCSourceFileAccess().getGroup_6_3(), "rule__CSourceFile__Group_6_3__0");
			builder.put(grammarAccess.getCSourceFileAccess().getGroup_7(), "rule__CSourceFile__Group_7__0");
			builder.put(grammarAccess.getCSourceFileAccess().getGroup_7_3(), "rule__CSourceFile__Group_7_3__0");
			builder.put(grammarAccess.getCSourceFileAccess().getGroup_8(), "rule__CSourceFile__Group_8__0");
			builder.put(grammarAccess.getCSourceFileAccess().getGroup_8_3(), "rule__CSourceFile__Group_8_3__0");
			builder.put(grammarAccess.getCHeaderFileAccess().getGroup(), "rule__CHeaderFile__Group__0");
			builder.put(grammarAccess.getCHeaderFileAccess().getGroup_4(), "rule__CHeaderFile__Group_4__0");
			builder.put(grammarAccess.getCHeaderFileAccess().getGroup_5(), "rule__CHeaderFile__Group_5__0");
			builder.put(grammarAccess.getCHeaderFileAccess().getGroup_5_3(), "rule__CHeaderFile__Group_5_3__0");
			builder.put(grammarAccess.getCHeaderFileAccess().getGroup_6(), "rule__CHeaderFile__Group_6__0");
			builder.put(grammarAccess.getCHeaderFileAccess().getGroup_6_3(), "rule__CHeaderFile__Group_6_3__0");
			builder.put(grammarAccess.getCHeaderFileAccess().getGroup_7(), "rule__CHeaderFile__Group_7__0");
			builder.put(grammarAccess.getCHeaderFileAccess().getGroup_7_3(), "rule__CHeaderFile__Group_7_3__0");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getGroup(), "rule__CSubProgram_Impl__Group__0");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getGroup_4(), "rule__CSubProgram_Impl__Group_4__0");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getGroup_5(), "rule__CSubProgram_Impl__Group_5__0");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getGroup_5_3(), "rule__CSubProgram_Impl__Group_5_3__0");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getGroup_6(), "rule__CSubProgram_Impl__Group_6__0");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getGroup_6_3(), "rule__CSubProgram_Impl__Group_6_3__0");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getGroup_7(), "rule__CSubProgram_Impl__Group_7__0");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getGroup_7_3(), "rule__CSubProgram_Impl__Group_7_3__0");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getGroup_8(), "rule__CSubProgram_Impl__Group_8__0");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getGroup_8_3(), "rule__CSubProgram_Impl__Group_8_3__0");
			builder.put(grammarAccess.getCVariable_ImplAccess().getGroup(), "rule__CVariable_Impl__Group__0");
			builder.put(grammarAccess.getCVariable_ImplAccess().getGroup_5(), "rule__CVariable_Impl__Group_5__0");
			builder.put(grammarAccess.getCVariable_ImplAccess().getGroup_6(), "rule__CVariable_Impl__Group_6__0");
			builder.put(grammarAccess.getCVariable_ImplAccess().getGroup_7(), "rule__CVariable_Impl__Group_7__0");
			builder.put(grammarAccess.getCType_ImplAccess().getGroup(), "rule__CType_Impl__Group__0");
			builder.put(grammarAccess.getCType_ImplAccess().getGroup_4(), "rule__CType_Impl__Group_4__0");
			builder.put(grammarAccess.getCIncludeDirectiveAccess().getGroup(), "rule__CIncludeDirective__Group__0");
			builder.put(grammarAccess.getCIncludeDirectiveAccess().getGroup_4(), "rule__CIncludeDirective__Group_4__0");
			builder.put(grammarAccess.getCIncludeDirectiveAccess().getGroup_5(), "rule__CIncludeDirective__Group_5__0");
			builder.put(grammarAccess.getCParameterAccess().getGroup(), "rule__CParameter__Group__0");
			builder.put(grammarAccess.getCParameterAccess().getGroup_4(), "rule__CParameter__Group_4__0");
			builder.put(grammarAccess.getCParameterAccess().getGroup_5(), "rule__CParameter__Group_5__0");
			builder.put(grammarAccess.getCExpression_ImplAccess().getGroup(), "rule__CExpression_Impl__Group__0");
			builder.put(grammarAccess.getCExpression_ImplAccess().getGroup_3(), "rule__CExpression_Impl__Group_3__0");
			builder.put(grammarAccess.getCPreConditionAccess().getGroup(), "rule__CPreCondition__Group__0");
			builder.put(grammarAccess.getCPreConditionAccess().getGroup_3(), "rule__CPreCondition__Group_3__0");
			builder.put(grammarAccess.getCPreConditionAccess().getGroup_4(), "rule__CPreCondition__Group_4__0");
			builder.put(grammarAccess.getCFunctionAccess().getGroup(), "rule__CFunction__Group__0");
			builder.put(grammarAccess.getCFunctionAccess().getGroup_4(), "rule__CFunction__Group_4__0");
			builder.put(grammarAccess.getCFunctionAccess().getGroup_5(), "rule__CFunction__Group_5__0");
			builder.put(grammarAccess.getCFunctionAccess().getGroup_6(), "rule__CFunction__Group_6__0");
			builder.put(grammarAccess.getCFunctionAccess().getGroup_6_3(), "rule__CFunction__Group_6_3__0");
			builder.put(grammarAccess.getCFunctionAccess().getGroup_7(), "rule__CFunction__Group_7__0");
			builder.put(grammarAccess.getCFunctionAccess().getGroup_7_3(), "rule__CFunction__Group_7_3__0");
			builder.put(grammarAccess.getCFunctionAccess().getGroup_8(), "rule__CFunction__Group_8__0");
			builder.put(grammarAccess.getCFunctionAccess().getGroup_8_3(), "rule__CFunction__Group_8_3__0");
			builder.put(grammarAccess.getCFunctionAccess().getGroup_9(), "rule__CFunction__Group_9__0");
			builder.put(grammarAccess.getCFunctionAccess().getGroup_9_3(), "rule__CFunction__Group_9_3__0");
			builder.put(grammarAccess.getCProcedureAccess().getGroup(), "rule__CProcedure__Group__0");
			builder.put(grammarAccess.getCProcedureAccess().getGroup_4(), "rule__CProcedure__Group_4__0");
			builder.put(grammarAccess.getCProcedureAccess().getGroup_5(), "rule__CProcedure__Group_5__0");
			builder.put(grammarAccess.getCProcedureAccess().getGroup_5_3(), "rule__CProcedure__Group_5_3__0");
			builder.put(grammarAccess.getCProcedureAccess().getGroup_6(), "rule__CProcedure__Group_6__0");
			builder.put(grammarAccess.getCProcedureAccess().getGroup_6_3(), "rule__CProcedure__Group_6_3__0");
			builder.put(grammarAccess.getCProcedureAccess().getGroup_7(), "rule__CProcedure__Group_7__0");
			builder.put(grammarAccess.getCProcedureAccess().getGroup_7_3(), "rule__CProcedure__Group_7_3__0");
			builder.put(grammarAccess.getCProcedureAccess().getGroup_8(), "rule__CProcedure__Group_8__0");
			builder.put(grammarAccess.getCProcedureAccess().getGroup_8_3(), "rule__CProcedure__Group_8_3__0");
			builder.put(grammarAccess.getCArrayVariableAccess().getGroup(), "rule__CArrayVariable__Group__0");
			builder.put(grammarAccess.getCArrayVariableAccess().getGroup_5(), "rule__CArrayVariable__Group_5__0");
			builder.put(grammarAccess.getCArrayVariableAccess().getGroup_6(), "rule__CArrayVariable__Group_6__0");
			builder.put(grammarAccess.getCArrayVariableAccess().getGroup_7(), "rule__CArrayVariable__Group_7__0");
			builder.put(grammarAccess.getCArrayVariableAccess().getGroup_8(), "rule__CArrayVariable__Group_8__0");
			builder.put(grammarAccess.getCArrayVariableAccess().getGroup_9(), "rule__CArrayVariable__Group_9__0");
			builder.put(grammarAccess.getCArrayVariableAccess().getGroup_10(), "rule__CArrayVariable__Group_10__0");
			builder.put(grammarAccess.getCArrayVariableAccess().getGroup_11(), "rule__CArrayVariable__Group_11__0");
			builder.put(grammarAccess.getCArrayVariableAccess().getGroup_11_3(), "rule__CArrayVariable__Group_11_3__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getCArrayElementAccess().getGroup(), "rule__CArrayElement__Group__0");
			builder.put(grammarAccess.getCArrayElementAccess().getGroup_4(), "rule__CArrayElement__Group_4__0");
			builder.put(grammarAccess.getCArrayElementAccess().getGroup_5(), "rule__CArrayElement__Group_5__0");
			builder.put(grammarAccess.getCArrayElementAccess().getGroup_6(), "rule__CArrayElement__Group_6__0");
			builder.put(grammarAccess.getCStructAccess().getGroup(), "rule__CStruct__Group__0");
			builder.put(grammarAccess.getCStructAccess().getGroup_4(), "rule__CStruct__Group_4__0");
			builder.put(grammarAccess.getCStructAccess().getGroup_5(), "rule__CStruct__Group_5__0");
			builder.put(grammarAccess.getCStructAccess().getGroup_6(), "rule__CStruct__Group_6__0");
			builder.put(grammarAccess.getCStructAccess().getGroup_7(), "rule__CStruct__Group_7__0");
			builder.put(grammarAccess.getCStructAccess().getGroup_7_3(), "rule__CStruct__Group_7_3__0");
			builder.put(grammarAccess.getCFieldAccess().getGroup(), "rule__CField__Group__0");
			builder.put(grammarAccess.getCFieldAccess().getGroup_4(), "rule__CField__Group_4__0");
			builder.put(grammarAccess.getCEnumerationAccess().getGroup(), "rule__CEnumeration__Group__0");
			builder.put(grammarAccess.getCEnumerationAccess().getGroup_4(), "rule__CEnumeration__Group_4__0");
			builder.put(grammarAccess.getCEnumerationAccess().getGroup_5(), "rule__CEnumeration__Group_5__0");
			builder.put(grammarAccess.getCEnumerationAccess().getGroup_5_3(), "rule__CEnumeration__Group_5_3__0");
			builder.put(grammarAccess.getCArray_ImplAccess().getGroup(), "rule__CArray_Impl__Group__0");
			builder.put(grammarAccess.getCArray_ImplAccess().getGroup_4(), "rule__CArray_Impl__Group_4__0");
			builder.put(grammarAccess.getCArray_ImplAccess().getGroup_5(), "rule__CArray_Impl__Group_5__0");
			builder.put(grammarAccess.getCArray_ImplAccess().getGroup_6(), "rule__CArray_Impl__Group_6__0");
			builder.put(grammarAccess.getCArray_ImplAccess().getGroup_7(), "rule__CArray_Impl__Group_7__0");
			builder.put(grammarAccess.getCArray_ImplAccess().getGroup_8(), "rule__CArray_Impl__Group_8__0");
			builder.put(grammarAccess.getCArray_ImplAccess().getGroup_8_3(), "rule__CArray_Impl__Group_8_3__0");
			builder.put(grammarAccess.getCPointerAccess().getGroup(), "rule__CPointer__Group__0");
			builder.put(grammarAccess.getCPointerAccess().getGroup_4(), "rule__CPointer__Group_4__0");
			builder.put(grammarAccess.getCPointerAccess().getGroup_5(), "rule__CPointer__Group_5__0");
			builder.put(grammarAccess.getCDerivedType_ImplAccess().getGroup(), "rule__CDerivedType_Impl__Group__0");
			builder.put(grammarAccess.getCDerivedType_ImplAccess().getGroup_4(), "rule__CDerivedType_Impl__Group_4__0");
			builder.put(grammarAccess.getCDerivedType_ImplAccess().getGroup_5(), "rule__CDerivedType_Impl__Group_5__0");
			builder.put(grammarAccess.getCDiscreteType_ImplAccess().getGroup(), "rule__CDiscreteType_Impl__Group__0");
			builder.put(grammarAccess.getCDiscreteType_ImplAccess().getGroup_4(), "rule__CDiscreteType_Impl__Group_4__0");
			builder.put(grammarAccess.getCEnumPropertiesAccess().getGroup(), "rule__CEnumProperties__Group__0");
			builder.put(grammarAccess.getCEnumPropertiesAccess().getGroup_4(), "rule__CEnumProperties__Group_4__0");
			builder.put(grammarAccess.getCEnumPropertiesAccess().getGroup_5(), "rule__CEnumProperties__Group_5__0");
			builder.put(grammarAccess.getCTranslationUnitAccess().getNameAssignment_2(), "rule__CTranslationUnit__NameAssignment_2");
			builder.put(grammarAccess.getCTranslationUnitAccess().getEndnameAssignment_4_1(), "rule__CTranslationUnit__EndnameAssignment_4_1");
			builder.put(grammarAccess.getCTranslationUnitAccess().getSourceFilesAssignment_5_2(), "rule__CTranslationUnit__SourceFilesAssignment_5_2");
			builder.put(grammarAccess.getCTranslationUnitAccess().getSourceFilesAssignment_5_3_1(), "rule__CTranslationUnit__SourceFilesAssignment_5_3_1");
			builder.put(grammarAccess.getCTranslationUnitAccess().getHeaderFilesAssignment_6_2(), "rule__CTranslationUnit__HeaderFilesAssignment_6_2");
			builder.put(grammarAccess.getCTranslationUnitAccess().getHeaderFilesAssignment_6_3_1(), "rule__CTranslationUnit__HeaderFilesAssignment_6_3_1");
			builder.put(grammarAccess.getCSourceFileAccess().getNameAssignment_2(), "rule__CSourceFile__NameAssignment_2");
			builder.put(grammarAccess.getCSourceFileAccess().getEndnameAssignment_4_1(), "rule__CSourceFile__EndnameAssignment_4_1");
			builder.put(grammarAccess.getCSourceFileAccess().getSubProgramsAssignment_5_2(), "rule__CSourceFile__SubProgramsAssignment_5_2");
			builder.put(grammarAccess.getCSourceFileAccess().getSubProgramsAssignment_5_3_1(), "rule__CSourceFile__SubProgramsAssignment_5_3_1");
			builder.put(grammarAccess.getCSourceFileAccess().getGlobalVariablesAssignment_6_2(), "rule__CSourceFile__GlobalVariablesAssignment_6_2");
			builder.put(grammarAccess.getCSourceFileAccess().getGlobalVariablesAssignment_6_3_1(), "rule__CSourceFile__GlobalVariablesAssignment_6_3_1");
			builder.put(grammarAccess.getCSourceFileAccess().getTypesAssignment_7_2(), "rule__CSourceFile__TypesAssignment_7_2");
			builder.put(grammarAccess.getCSourceFileAccess().getTypesAssignment_7_3_1(), "rule__CSourceFile__TypesAssignment_7_3_1");
			builder.put(grammarAccess.getCSourceFileAccess().getIncludeDirectivesAssignment_8_2(), "rule__CSourceFile__IncludeDirectivesAssignment_8_2");
			builder.put(grammarAccess.getCSourceFileAccess().getIncludeDirectivesAssignment_8_3_1(), "rule__CSourceFile__IncludeDirectivesAssignment_8_3_1");
			builder.put(grammarAccess.getCHeaderFileAccess().getNameAssignment_2(), "rule__CHeaderFile__NameAssignment_2");
			builder.put(grammarAccess.getCHeaderFileAccess().getEndnameAssignment_4_1(), "rule__CHeaderFile__EndnameAssignment_4_1");
			builder.put(grammarAccess.getCHeaderFileAccess().getSubProgramsAssignment_5_2(), "rule__CHeaderFile__SubProgramsAssignment_5_2");
			builder.put(grammarAccess.getCHeaderFileAccess().getSubProgramsAssignment_5_3_1(), "rule__CHeaderFile__SubProgramsAssignment_5_3_1");
			builder.put(grammarAccess.getCHeaderFileAccess().getGlobalVariablesAssignment_6_2(), "rule__CHeaderFile__GlobalVariablesAssignment_6_2");
			builder.put(grammarAccess.getCHeaderFileAccess().getGlobalVariablesAssignment_6_3_1(), "rule__CHeaderFile__GlobalVariablesAssignment_6_3_1");
			builder.put(grammarAccess.getCHeaderFileAccess().getTypesAssignment_7_2(), "rule__CHeaderFile__TypesAssignment_7_2");
			builder.put(grammarAccess.getCHeaderFileAccess().getTypesAssignment_7_3_1(), "rule__CHeaderFile__TypesAssignment_7_3_1");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getNameAssignment_2(), "rule__CSubProgram_Impl__NameAssignment_2");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getEndnameAssignment_4_1(), "rule__CSubProgram_Impl__EndnameAssignment_4_1");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getParametersAssignment_5_2(), "rule__CSubProgram_Impl__ParametersAssignment_5_2");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getParametersAssignment_5_3_1(), "rule__CSubProgram_Impl__ParametersAssignment_5_3_1");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getLocalVariablesAssignment_6_2(), "rule__CSubProgram_Impl__LocalVariablesAssignment_6_2");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getLocalVariablesAssignment_6_3_1(), "rule__CSubProgram_Impl__LocalVariablesAssignment_6_3_1");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getBodyAssignment_7_2(), "rule__CSubProgram_Impl__BodyAssignment_7_2");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getBodyAssignment_7_3_1(), "rule__CSubProgram_Impl__BodyAssignment_7_3_1");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getPreconditionsAssignment_8_2(), "rule__CSubProgram_Impl__PreconditionsAssignment_8_2");
			builder.put(grammarAccess.getCSubProgram_ImplAccess().getPreconditionsAssignment_8_3_1(), "rule__CSubProgram_Impl__PreconditionsAssignment_8_3_1");
			builder.put(grammarAccess.getCVariable_ImplAccess().getIsConstantAssignment_1(), "rule__CVariable_Impl__IsConstantAssignment_1");
			builder.put(grammarAccess.getCVariable_ImplAccess().getNameAssignment_3(), "rule__CVariable_Impl__NameAssignment_3");
			builder.put(grammarAccess.getCVariable_ImplAccess().getEndnameAssignment_5_1(), "rule__CVariable_Impl__EndnameAssignment_5_1");
			builder.put(grammarAccess.getCVariable_ImplAccess().getValueAssignment_6_1(), "rule__CVariable_Impl__ValueAssignment_6_1");
			builder.put(grammarAccess.getCVariable_ImplAccess().getTypeAssignment_7_1(), "rule__CVariable_Impl__TypeAssignment_7_1");
			builder.put(grammarAccess.getCType_ImplAccess().getNameAssignment_2(), "rule__CType_Impl__NameAssignment_2");
			builder.put(grammarAccess.getCType_ImplAccess().getEndnameAssignment_4_1(), "rule__CType_Impl__EndnameAssignment_4_1");
			builder.put(grammarAccess.getCIncludeDirectiveAccess().getNameAssignment_2(), "rule__CIncludeDirective__NameAssignment_2");
			builder.put(grammarAccess.getCIncludeDirectiveAccess().getEndnameAssignment_4_1(), "rule__CIncludeDirective__EndnameAssignment_4_1");
			builder.put(grammarAccess.getCIncludeDirectiveAccess().getHeaderAssignment_5_1(), "rule__CIncludeDirective__HeaderAssignment_5_1");
			builder.put(grammarAccess.getCParameterAccess().getNameAssignment_2(), "rule__CParameter__NameAssignment_2");
			builder.put(grammarAccess.getCParameterAccess().getEndnameAssignment_4_1(), "rule__CParameter__EndnameAssignment_4_1");
			builder.put(grammarAccess.getCParameterAccess().getTypeAssignment_5_1(), "rule__CParameter__TypeAssignment_5_1");
			builder.put(grammarAccess.getCExpression_ImplAccess().getExpressionAssignment_3_1(), "rule__CExpression_Impl__ExpressionAssignment_3_1");
			builder.put(grammarAccess.getCPreConditionAccess().getExpressionAssignment_3_1(), "rule__CPreCondition__ExpressionAssignment_3_1");
			builder.put(grammarAccess.getCPreConditionAccess().getPredicateAssignment_4_1(), "rule__CPreCondition__PredicateAssignment_4_1");
			builder.put(grammarAccess.getCFunctionAccess().getNameAssignment_2(), "rule__CFunction__NameAssignment_2");
			builder.put(grammarAccess.getCFunctionAccess().getEndnameAssignment_4_1(), "rule__CFunction__EndnameAssignment_4_1");
			builder.put(grammarAccess.getCFunctionAccess().getReturnTypeAssignment_5_1(), "rule__CFunction__ReturnTypeAssignment_5_1");
			builder.put(grammarAccess.getCFunctionAccess().getParametersAssignment_6_2(), "rule__CFunction__ParametersAssignment_6_2");
			builder.put(grammarAccess.getCFunctionAccess().getParametersAssignment_6_3_1(), "rule__CFunction__ParametersAssignment_6_3_1");
			builder.put(grammarAccess.getCFunctionAccess().getLocalVariablesAssignment_7_2(), "rule__CFunction__LocalVariablesAssignment_7_2");
			builder.put(grammarAccess.getCFunctionAccess().getLocalVariablesAssignment_7_3_1(), "rule__CFunction__LocalVariablesAssignment_7_3_1");
			builder.put(grammarAccess.getCFunctionAccess().getBodyAssignment_8_2(), "rule__CFunction__BodyAssignment_8_2");
			builder.put(grammarAccess.getCFunctionAccess().getBodyAssignment_8_3_1(), "rule__CFunction__BodyAssignment_8_3_1");
			builder.put(grammarAccess.getCFunctionAccess().getPreconditionsAssignment_9_2(), "rule__CFunction__PreconditionsAssignment_9_2");
			builder.put(grammarAccess.getCFunctionAccess().getPreconditionsAssignment_9_3_1(), "rule__CFunction__PreconditionsAssignment_9_3_1");
			builder.put(grammarAccess.getCProcedureAccess().getNameAssignment_2(), "rule__CProcedure__NameAssignment_2");
			builder.put(grammarAccess.getCProcedureAccess().getEndnameAssignment_4_1(), "rule__CProcedure__EndnameAssignment_4_1");
			builder.put(grammarAccess.getCProcedureAccess().getParametersAssignment_5_2(), "rule__CProcedure__ParametersAssignment_5_2");
			builder.put(grammarAccess.getCProcedureAccess().getParametersAssignment_5_3_1(), "rule__CProcedure__ParametersAssignment_5_3_1");
			builder.put(grammarAccess.getCProcedureAccess().getLocalVariablesAssignment_6_2(), "rule__CProcedure__LocalVariablesAssignment_6_2");
			builder.put(grammarAccess.getCProcedureAccess().getLocalVariablesAssignment_6_3_1(), "rule__CProcedure__LocalVariablesAssignment_6_3_1");
			builder.put(grammarAccess.getCProcedureAccess().getBodyAssignment_7_2(), "rule__CProcedure__BodyAssignment_7_2");
			builder.put(grammarAccess.getCProcedureAccess().getBodyAssignment_7_3_1(), "rule__CProcedure__BodyAssignment_7_3_1");
			builder.put(grammarAccess.getCProcedureAccess().getPreconditionsAssignment_8_2(), "rule__CProcedure__PreconditionsAssignment_8_2");
			builder.put(grammarAccess.getCProcedureAccess().getPreconditionsAssignment_8_3_1(), "rule__CProcedure__PreconditionsAssignment_8_3_1");
			builder.put(grammarAccess.getCArrayVariableAccess().getIsConstantAssignment_1(), "rule__CArrayVariable__IsConstantAssignment_1");
			builder.put(grammarAccess.getCArrayVariableAccess().getNameAssignment_3(), "rule__CArrayVariable__NameAssignment_3");
			builder.put(grammarAccess.getCArrayVariableAccess().getEndnameAssignment_5_1(), "rule__CArrayVariable__EndnameAssignment_5_1");
			builder.put(grammarAccess.getCArrayVariableAccess().getValueAssignment_6_1(), "rule__CArrayVariable__ValueAssignment_6_1");
			builder.put(grammarAccess.getCArrayVariableAccess().getTypeAssignment_7_1(), "rule__CArrayVariable__TypeAssignment_7_1");
			builder.put(grammarAccess.getCArrayVariableAccess().getElementTypeAssignment_8_1(), "rule__CArrayVariable__ElementTypeAssignment_8_1");
			builder.put(grammarAccess.getCArrayVariableAccess().getSizeAssignment_9_1(), "rule__CArrayVariable__SizeAssignment_9_1");
			builder.put(grammarAccess.getCArrayVariableAccess().getSuperTypeAssignment_10_1(), "rule__CArrayVariable__SuperTypeAssignment_10_1");
			builder.put(grammarAccess.getCArrayVariableAccess().getArrayElementsAssignment_11_2(), "rule__CArrayVariable__ArrayElementsAssignment_11_2");
			builder.put(grammarAccess.getCArrayVariableAccess().getArrayElementsAssignment_11_3_1(), "rule__CArrayVariable__ArrayElementsAssignment_11_3_1");
			builder.put(grammarAccess.getCArrayElementAccess().getNameAssignment_2(), "rule__CArrayElement__NameAssignment_2");
			builder.put(grammarAccess.getCArrayElementAccess().getEndnameAssignment_4_1(), "rule__CArrayElement__EndnameAssignment_4_1");
			builder.put(grammarAccess.getCArrayElementAccess().getIndexAssignment_5_1(), "rule__CArrayElement__IndexAssignment_5_1");
			builder.put(grammarAccess.getCArrayElementAccess().getValueAssignment_6_1(), "rule__CArrayElement__ValueAssignment_6_1");
			builder.put(grammarAccess.getCStructAccess().getNameAssignment_2(), "rule__CStruct__NameAssignment_2");
			builder.put(grammarAccess.getCStructAccess().getEndnameAssignment_4_1(), "rule__CStruct__EndnameAssignment_4_1");
			builder.put(grammarAccess.getCStructAccess().getTypeAssignment_5_1(), "rule__CStruct__TypeAssignment_5_1");
			builder.put(grammarAccess.getCStructAccess().getSuperTypeAssignment_6_1(), "rule__CStruct__SuperTypeAssignment_6_1");
			builder.put(grammarAccess.getCStructAccess().getFieldsAssignment_7_2(), "rule__CStruct__FieldsAssignment_7_2");
			builder.put(grammarAccess.getCStructAccess().getFieldsAssignment_7_3_1(), "rule__CStruct__FieldsAssignment_7_3_1");
			builder.put(grammarAccess.getCFieldAccess().getNameAssignment_2(), "rule__CField__NameAssignment_2");
			builder.put(grammarAccess.getCFieldAccess().getEndnameAssignment_4_1(), "rule__CField__EndnameAssignment_4_1");
			builder.put(grammarAccess.getCEnumerationAccess().getNameAssignment_2(), "rule__CEnumeration__NameAssignment_2");
			builder.put(grammarAccess.getCEnumerationAccess().getEndnameAssignment_4_1(), "rule__CEnumeration__EndnameAssignment_4_1");
			builder.put(grammarAccess.getCEnumerationAccess().getEnumPropertiesAssignment_5_2(), "rule__CEnumeration__EnumPropertiesAssignment_5_2");
			builder.put(grammarAccess.getCEnumerationAccess().getEnumPropertiesAssignment_5_3_1(), "rule__CEnumeration__EnumPropertiesAssignment_5_3_1");
			builder.put(grammarAccess.getCArray_ImplAccess().getNameAssignment_2(), "rule__CArray_Impl__NameAssignment_2");
			builder.put(grammarAccess.getCArray_ImplAccess().getEndnameAssignment_4_1(), "rule__CArray_Impl__EndnameAssignment_4_1");
			builder.put(grammarAccess.getCArray_ImplAccess().getElementTypeAssignment_5_1(), "rule__CArray_Impl__ElementTypeAssignment_5_1");
			builder.put(grammarAccess.getCArray_ImplAccess().getSizeAssignment_6_1(), "rule__CArray_Impl__SizeAssignment_6_1");
			builder.put(grammarAccess.getCArray_ImplAccess().getSuperTypeAssignment_7_1(), "rule__CArray_Impl__SuperTypeAssignment_7_1");
			builder.put(grammarAccess.getCArray_ImplAccess().getArrayElementsAssignment_8_2(), "rule__CArray_Impl__ArrayElementsAssignment_8_2");
			builder.put(grammarAccess.getCArray_ImplAccess().getArrayElementsAssignment_8_3_1(), "rule__CArray_Impl__ArrayElementsAssignment_8_3_1");
			builder.put(grammarAccess.getCPointerAccess().getNameAssignment_2(), "rule__CPointer__NameAssignment_2");
			builder.put(grammarAccess.getCPointerAccess().getEndnameAssignment_4_1(), "rule__CPointer__EndnameAssignment_4_1");
			builder.put(grammarAccess.getCPointerAccess().getSuperTypeAssignment_5_1(), "rule__CPointer__SuperTypeAssignment_5_1");
			builder.put(grammarAccess.getCDerivedType_ImplAccess().getNameAssignment_2(), "rule__CDerivedType_Impl__NameAssignment_2");
			builder.put(grammarAccess.getCDerivedType_ImplAccess().getEndnameAssignment_4_1(), "rule__CDerivedType_Impl__EndnameAssignment_4_1");
			builder.put(grammarAccess.getCDerivedType_ImplAccess().getSuperTypeAssignment_5_1(), "rule__CDerivedType_Impl__SuperTypeAssignment_5_1");
			builder.put(grammarAccess.getCDiscreteType_ImplAccess().getNameAssignment_2(), "rule__CDiscreteType_Impl__NameAssignment_2");
			builder.put(grammarAccess.getCDiscreteType_ImplAccess().getEndnameAssignment_4_1(), "rule__CDiscreteType_Impl__EndnameAssignment_4_1");
			builder.put(grammarAccess.getCEnumPropertiesAccess().getNameAssignment_2(), "rule__CEnumProperties__NameAssignment_2");
			builder.put(grammarAccess.getCEnumPropertiesAccess().getEndnameAssignment_4_1(), "rule__CEnumProperties__EndnameAssignment_4_1");
			builder.put(grammarAccess.getCEnumPropertiesAccess().getIntegralConstantAssignment_5_1(), "rule__CEnumProperties__IntegralConstantAssignment_5_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private XcGrammarAccess grammarAccess;

	@Override
	protected InternalXcParser createParser() {
		InternalXcParser result = new InternalXcParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public XcGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XcGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
