<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecore" nsURI="http://ac/soton/eventb/c" nsPrefix="ac.soton.eventb.c">
  <eClassifiers xsi:type="ecore:EClass" name="CNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CType" eSuperTypes="#//CNamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CVariable" eSuperTypes="#//CNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConstant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CStruct" eSuperTypes="#//CDerivedType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//CField" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CField" eSuperTypes="#//CNamedElement #//CType"/>
  <eClassifiers xsi:type="ecore:EClass" name="CEnumeration" eSuperTypes="#//CDiscreteType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumProperties" upperBound="-1"
        eType="#//CEnumProperties" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CEnumProperties" eSuperTypes="#//CNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="integralConstant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CArray" eSuperTypes="#//CDerivedType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrayElements" upperBound="-1"
        eType="#//CArrayElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CArrayElement" eSuperTypes="#//CNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CPointer" eSuperTypes="#//CDerivedType"/>
  <eClassifiers xsi:type="ecore:EClass" name="CExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CSubProgram" eSuperTypes="#//CNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//CParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localVariables" upperBound="-1"
        eType="#//CVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" upperBound="-1" eType="#//CExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preconditions" upperBound="-1"
        eType="#//CPreCondition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CDerivedType" eSuperTypes="#//CType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//CType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CDiscreteType" eSuperTypes="#//CType"/>
  <eClassifiers xsi:type="ecore:EClass" name="CParameter" eSuperTypes="#//CNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CFunction" eSuperTypes="#//CSubProgram">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CProcedure" eSuperTypes="#//CSubProgram"/>
  <eClassifiers xsi:type="ecore:EClass" name="CTranslationUnit" eSuperTypes="#//CNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceFiles" upperBound="-1"
        eType="#//CSourceFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="headerFiles" upperBound="-1"
        eType="#//CHeaderFile" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CSourceFile" eSuperTypes="#//CFile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="includeDirectives" upperBound="-1"
        eType="#//CIncludeDirective" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CHeaderFile" eSuperTypes="#//CFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="CIncludeDirective" eSuperTypes="#//CNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="header" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CFile" eSuperTypes="#//CNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subPrograms" upperBound="-1"
        eType="#//CSubProgram" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalVariables" upperBound="-1"
        eType="#//CVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//CType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CArrayVariable" eSuperTypes="#//CVariable #//CArray"/>
  <eClassifiers xsi:type="ecore:EClass" name="CPreCondition" eSuperTypes="#//CExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="predicate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
