/*
 * generated by Xtext 2.25.0
 */
package ac.soton.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class XcStandaloneSetup extends XcStandaloneSetupGenerated {

	public static void doSetup() {
		new XcStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
